print("Hello, World!")
print("Thanaboon Imcahroen")
print("i'm hungry")
print("im'good \"And I'm fine\"")
print("/\\")
#print("Hello, World!\nThanaboon Imcahroen\nI'm hungry\nI'm good \"And I'm fine\"\n/\\")